### PR TITLE
Ds3

### PR DESCRIPTION
**Pull request by malvadeza**
- Testes para DatabaseSearcher e SeachQuery
- Testes passando

### CODE REVIEW

**Comment by koppor** [comment]
This pull request reads interesting. Would you be interested in bringing this test to the [JabRef main repository](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md)? (With English code comments :))

**Comment by malvadeza** [comment]
@koppor So, I just need to translate the commit messages (also the PR message)?

**Comment by koppor** [comment]
IMHO, the steps are:
1. Create a fork from https://github.com/jabref/jabref/
2. Create a new branch `add-search-test-cases`
3. Add your two new test files there
4. Add your modifications to SearchQueryTest.java
5. Create a commit with an English commit message. It could be "Add more tests to Search"
6. Create a pull request (useful links: https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md)
7. Hope that the other developers also like it. I think so. :innocent:

**Comment by malvadeza** [comment]
@koppor Thanks! Will do!

**Comment by koppor** [comment]
I did it for myself in https://github.com/JabRef/jabref/pull/1976

**Pull request closed without merging**
